const COLOR_DATA = [
  // --- Rouges ---
  { name: "Rouge", hex: "#FF0000", category: "Rouges" },
  { name: "Cramoisi", hex: "#DC143C", category: "Rouges" },
  { name: "Rouge Indien", hex: "#CD5C5C", category: "Rouges" },
  { name: "Saumon Clair", hex: "#FFA07A", category: "Rouges" },
  { name: "Saumon", hex: "#FA8072", category: "Rouges" },
  { name: "Saumon Foncé", hex: "#E9967A", category: "Rouges" },
  { name: "Rouge Foncé", hex: "#8B0000", category: "Rouges" },
  { name: "Brique Réfractaire", hex: "#B22222", category: "Rouges" },
  { name: "Tomate", hex: "#FF6347", category: "Rouges" },
  { name: "Corail", hex: "#FF7F50", category: "Rouges" },
  { name: "Vermillon", hex: "#E34234", category: "Rouges" },
  { name: "Carmin", hex: "#960018", category: "Rouges" },
  { name: "Bordeaux", hex: "#6D071A", category: "Rouges" },
  { name: "Grenat", hex: "#6E0B14", category: "Rouges" },
  { name: "Cerise", hex: "#DE3163", category: "Rouges" },
  { name: "Framboise", hex: "#E30B5C", category: "Rouges" },
  { name: "Coquelicot", hex: "#C60800", category: "Rouges" },
  { name: "Écarlate", hex: "#FF2400", category: "Rouges" },

  // --- Roses ---
  { name: "Rose", hex: "#FFC0CB", category: "Roses" },
  { name: "Rose Vif", hex: "#FF69B4", category: "Roses" },
  { name: "Rose Profond", hex: "#FF1493", category: "Roses" },
  { name: "Rose Pâle", hex: "#FFB6C1", category: "Roses" },
  { name: "Rose Moyen", hex: "#C71585", category: "Roses" },
  { name: "Fuchsia", hex: "#FF00FF", category: "Roses" },
  { name: "Magenta", hex: "#FF0090", category: "Roses" },
  { name: "Vieux Rose", hex: "#C08081", category: "Roses" },
  { name: "Rose Bonbon", hex: "#F9429E", category: "Roses" },
  { name: "Rose Dragée", hex: "#FEBFD2", category: "Roses" },
  { name: "Rose Poudré", hex: "#E8CCD7", category: "Roses" },
  { name: "Rose Thé", hex: "#FF866A", category: "Roses" },
  { name: "Rose Fraise", hex: "#EC5E6F", category: "Roses" },

  // --- Oranges ---
  { name: "Orange", hex: "#FFA500", category: "Oranges" },
  { name: "Orange Foncé", hex: "#FF8C00", category: "Oranges" },
  { name: "Orange Rouge", hex: "#FF4500", category: "Oranges" },
  { name: "Mandarine", hex: "#FEA347", category: "Oranges" },
  { name: "Abricot", hex: "#E67E30", category: "Oranges" },
  { name: "Citrouille", hex: "#DF6D14", category: "Oranges" },
  { name: "Carotte", hex: "#F4661B", category: "Oranges" },
  { name: "Rouille", hex: "#985717", category: "Oranges" },
  { name: "Terre Cuite", hex: "#CC5500", category: "Oranges" },
  { name: "Papaye", hex: "#FFEFD5", category: "Oranges" },
  { name: "Pêche", hex: "#FFDAB9", category: "Oranges" },
  { name: "Ambre", hex: "#F0C300", category: "Oranges" },
  { name: "Cuivre", hex: "#B87333", category: "Oranges" },

  // --- Jaunes ---
  { name: "Jaune", hex: "#FFFF00", category: "Jaunes" },
  { name: "Jaune Clair", hex: "#FFFFE0", category: "Jaunes" },
  { name: "Jaune Citron", hex: "#FFF44F", category: "Jaunes" },
  { name: "Or", hex: "#FFD700", category: "Jaunes" },
  { name: "Jaune Doré", hex: "#FFC125", category: "Jaunes" },
  { name: "Moutarde", hex: "#FFDB58", category: "Jaunes" },
  { name: "Jaune Paille", hex: "#FEE347", category: "Jaunes" },
  { name: "Blé", hex: "#F5DEB3", category: "Jaunes" },
  { name: "Safran", hex: "#F4C430", category: "Jaunes" },
  { name: "Tournesol", hex: "#FFDA03", category: "Jaunes" },
  { name: "Banane", hex: "#FFE135", category: "Jaunes" },
  { name: "Canari", hex: "#E7F00D", category: "Jaunes" },
  { name: "Champagne", hex: "#F7E7CE", category: "Jaunes" },
  { name: "Crème", hex: "#FFFDD0", category: "Jaunes" },

  // --- Verts ---
  { name: "Vert", hex: "#008000", category: "Verts" },
  { name: "Vert Citron", hex: "#32CD32", category: "Verts" },
  { name: "Vert Lime", hex: "#00FF00", category: "Verts" },
  { name: "Vert Foncé", hex: "#006400", category: "Verts" },
  { name: "Vert Forêt", hex: "#228B22", category: "Verts" },
  { name: "Vert Olive", hex: "#808000", category: "Verts" },
  { name: "Olive Foncé", hex: "#556B2F", category: "Verts" },
  { name: "Vert Jaune", hex: "#ADFF2F", category: "Verts" },
  { name: "Chartreuse", hex: "#7FFF00", category: "Verts" },
  { name: "Vert Printemps", hex: "#00FF7F", category: "Verts" },
  { name: "Vert Mer Moyen", hex: "#3CB371", category: "Verts" },
  { name: "Vert Mer", hex: "#2E8B57", category: "Verts" },
  { name: "Vert Menthe", hex: "#98FF98", category: "Verts" },
  { name: "Émeraude", hex: "#50C878", category: "Verts" },
  { name: "Jade", hex: "#00A86B", category: "Verts" },
  { name: "Sapin", hex: "#095228", category: "Verts" },
  { name: "Vert Sauge", hex: "#689D71", category: "Verts" },
  { name: "Vert Militaire", hex: "#596643", category: "Verts" },
  { name: "Vert Pomme", hex: "#34C924", category: "Verts" },
  { name: "Pistache", hex: "#BEF574", category: "Verts" },
  { name: "Tilleul", hex: "#A5D152", category: "Verts" },
  { name: "Kaki", hex: "#94812B", category: "Verts" },

  // --- Cyans ---
  { name: "Cyan", hex: "#00FFFF", category: "Cyans" },
  { name: "Cyan Foncé", hex: "#008B8B", category: "Cyans" },
  { name: "Turquoise", hex: "#40E0D0", category: "Cyans" },
  { name: "Turquoise Foncé", hex: "#00CED1", category: "Cyans" },
  { name: "Turquoise Moyen", hex: "#48D1CC", category: "Cyans" },
  { name: "Aigue-Marine", hex: "#7FFFD4", category: "Cyans" },
  { name: "Sarcelle", hex: "#008080", category: "Cyans" },
  { name: "Bleu Cadet", hex: "#5F9EA0", category: "Cyans" },
  { name: "Vert d'Eau", hex: "#B0F4E6", category: "Cyans" },
  { name: "Céladon", hex: "#ACE1AF", category: "Cyans" },
  { name: "Lagon", hex: "#20B2AA", category: "Cyans" },
  { name: "Bleu Canard", hex: "#048B9A", category: "Cyans" },

  // --- Bleus ---
  { name: "Bleu", hex: "#0000FF", category: "Bleus" },
  { name: "Bleu Royal", hex: "#4169E1", category: "Bleus" },
  { name: "Bleu Marine", hex: "#000080", category: "Bleus" },
  { name: "Bleu Foncé", hex: "#00008B", category: "Bleus" },
  { name: "Bleu Moyen", hex: "#0000CD", category: "Bleus" },
  { name: "Bleu Ciel", hex: "#87CEEB", category: "Bleus" },
  { name: "Bleu Clair", hex: "#ADD8E6", category: "Bleus" },
  { name: "Bleu Poudré", hex: "#B0E0E6", category: "Bleus" },
  { name: "Bleu Acier", hex: "#4682B4", category: "Bleus" },
  { name: "Bleu Nuit", hex: "#191970", category: "Bleus" },
  { name: "Bleu Bleuet", hex: "#6495ED", category: "Bleus" },
  { name: "Bleu Dodger", hex: "#1E90FF", category: "Bleus" },
  { name: "Bleu Cobalt", hex: "#0047AB", category: "Bleus" },
  { name: "Bleu Saphir", hex: "#0131B4", category: "Bleus" },
  { name: "Bleu Azur", hex: "#007FFF", category: "Bleus" },
  { name: "Bleu Cérulé", hex: "#357AB7", category: "Bleus" },
  { name: "Bleu Outremer", hex: "#120A8F", category: "Bleus" },
  { name: "Bleu Klein", hex: "#002FA7", category: "Bleus" },
  { name: "Bleu Pétrole", hex: "#1D4E5F", category: "Bleus" },
  { name: "Bleu Glacier", hex: "#6E99C4", category: "Bleus" },
  { name: "Bleu Électrique", hex: "#2C75FF", category: "Bleus" },
  { name: "Pervenche", hex: "#CCCCFF", category: "Bleus" },

  // --- Violets ---
  { name: "Violet", hex: "#EE82EE", category: "Violets" },
  { name: "Violet Foncé", hex: "#9400D3", category: "Violets" },
  { name: "Pourpre", hex: "#800080", category: "Violets" },
  { name: "Indigo", hex: "#4B0082", category: "Violets" },
  { name: "Orchidée", hex: "#DA70D6", category: "Violets" },
  { name: "Orchidée Foncé", hex: "#9932CC", category: "Violets" },
  { name: "Orchidée Moyen", hex: "#BA55D3", category: "Violets" },
  { name: "Prune", hex: "#DDA0DD", category: "Violets" },
  { name: "Mauve", hex: "#D473D4", category: "Violets" },
  { name: "Lavande", hex: "#E6E6FA", category: "Violets" },
  { name: "Chardon", hex: "#D8BFD8", category: "Violets" },
  { name: "Bleu Violet", hex: "#8A2BE2", category: "Violets" },
  { name: "Améthyste", hex: "#9966CC", category: "Violets" },
  { name: "Lilas", hex: "#B666D2", category: "Violets" },
  { name: "Aubergine", hex: "#370028", category: "Violets" },
  { name: "Byzantin", hex: "#702963", category: "Violets" },
  { name: "Parme", hex: "#CFA0E9", category: "Violets" },

  // --- Marrons ---
  { name: "Marron", hex: "#A0522D", category: "Marrons" },
  { name: "Brun", hex: "#8B4513", category: "Marrons" },
  { name: "Chocolat", hex: "#D2691E", category: "Marrons" },
  { name: "Noisette", hex: "#955628", category: "Marrons" },
  { name: "Châtain", hex: "#8B6914", category: "Marrons" },
  { name: "Cannelle", hex: "#7E5835", category: "Marrons" },
  { name: "Sépia", hex: "#704214", category: "Marrons" },
  { name: "Café", hex: "#462E01", category: "Marrons" },
  { name: "Caramel", hex: "#7E3817", category: "Marrons" },
  { name: "Acajou", hex: "#88421D", category: "Marrons" },
  { name: "Terre de Sienne", hex: "#A0522D", category: "Marrons" },
  { name: "Ocre", hex: "#C08040", category: "Marrons" },
  { name: "Bistre", hex: "#856D4D", category: "Marrons" },
  { name: "Beige", hex: "#F5F5DC", category: "Marrons" },
  { name: "Sable", hex: "#E0CDA9", category: "Marrons" },
  { name: "Havane", hex: "#A67D3D", category: "Marrons" },
  { name: "Fauve", hex: "#AD4F09", category: "Marrons" },

  // --- Blancs ---
  { name: "Blanc", hex: "#FFFFFF", category: "Blancs" },
  { name: "Blanc Neige", hex: "#FFFAFA", category: "Blancs" },
  { name: "Blanc Floral", hex: "#FFFAF0", category: "Blancs" },
  { name: "Blanc Fantôme", hex: "#F8F8FF", category: "Blancs" },
  { name: "Ivoire", hex: "#FFFFF0", category: "Blancs" },
  { name: "Lin", hex: "#FAF0E6", category: "Blancs" },
  { name: "Blanc Antique", hex: "#FAEBD7", category: "Blancs" },
  { name: "Coquille d'Œuf", hex: "#FFF8DC", category: "Blancs" },
  { name: "Blanc Lavande", hex: "#FFF0F5", category: "Blancs" },
  { name: "Albâtre", hex: "#F2F0E6", category: "Blancs" },
  { name: "Nacre", hex: "#FDE9E0", category: "Blancs" },
  { name: "Blanc Cassé", hex: "#FEFEE2", category: "Blancs" },

  // --- Gris ---
  { name: "Gris", hex: "#808080", category: "Gris" },
  { name: "Gris Clair", hex: "#D3D3D3", category: "Gris" },
  { name: "Gris Foncé", hex: "#A9A9A9", category: "Gris" },
  { name: "Gris Ardoise", hex: "#708090", category: "Gris" },
  { name: "Gris Ardoise Foncé", hex: "#2F4F4F", category: "Gris" },
  { name: "Gris Argenté", hex: "#C0C0C0", category: "Gris" },
  { name: "Argent", hex: "#C0C0C0", category: "Gris" },
  { name: "Gainsboro", hex: "#DCDCDC", category: "Gris" },
  { name: "Gris Fumée", hex: "#F5F5F5", category: "Gris" },
  { name: "Gris Perle", hex: "#CECECE", category: "Gris" },
  { name: "Gris Anthracite", hex: "#303030", category: "Gris" },
  { name: "Gris Souris", hex: "#9E9E9E", category: "Gris" },
  { name: "Gris Acier", hex: "#71797E", category: "Gris" },
  { name: "Étain", hex: "#A8A9AD", category: "Gris" },
  { name: "Plomb", hex: "#595959", category: "Gris" },

  // --- Noirs ---
  { name: "Noir", hex: "#000000", category: "Noirs" },
  { name: "Noir d'Encre", hex: "#1B1B1B", category: "Noirs" },
  { name: "Noir Charbon", hex: "#1C1C1C", category: "Noirs" },
  { name: "Noir Ébène", hex: "#0C0C0C", category: "Noirs" },
  { name: "Noir Jais", hex: "#0A0A0A", category: "Noirs" },
  { name: "Noir Réglisse", hex: "#181818", category: "Noirs" },
  { name: "Onyx", hex: "#0F0F0F", category: "Noirs" },
  { name: "Noir Corbeau", hex: "#050505", category: "Noirs" },
];
